services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: phone-catalogue-backend-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - FRONTEND_URL=http://localhost:5173
    volumes:
      # Mount entire backend for development with hot reload
      - ./backend:/app
      - /app/node_modules
    networks:
      - phone-catalogue-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    container_name: phone-catalogue-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000/api
    volumes:
      # Mount entire frontend for development with hot reload
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - phone-catalogue-network
    restart: unless-stopped

networks:
  phone-catalogue-network:
    driver: bridge
    name: phone-catalogue-network-dev
